name: OWASP Dependency Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Download Dependency-Check
        run: |
         curl -L https://github.com/dependency-check/DependencyCheck/releases/download/v12.2.2/dependency-check-12.2.2-release.zip -o dependency-check.zip
         unzip dependency-check.zip

      - name: Run Dependency Check
        run: |
          ./dependency-check/bin/dependency-check.sh \
            --project "SMElevate" \
            --scan . \
            --format HTML \
            --out reports

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/